### PR TITLE
Updating my old deleted user with new

### PR DESCRIPTION
**Pull request by Azymous**
Updating it because i deleted that account but making this change just so no one re-makes the account with that name because that would make the link take to fake profile.

### CODE REVIEW

**Comment by bls1999** [comment]
Can you verify somehow that you're Dex472? It's a bad precedent for me to set to start changing contributor names around.

**Comment by Azymous** [comment]
@bls1999 I have sent you friend invite in discord as Azymous, i can prove being Dex472 (Gerrya8) by showing i have the pr2 accounts you know me having.

**Comment by bls1999** [comment]
@Azymous I didn't get anything from you

**Comment by Azymous** [comment]
@bls1999 Is there any other ways i could verify it being me?

**Comment by bls1999** [comment]
This is the last time I will be approving a pull request to change your name in the list of contributors.

**Pull request merged**
