### PR TITLE
Fix for issue #121

### PR DESCRIPTION
**Pull request by fourst4r**
farewell sim detector

### CODE REVIEW

**Comment by jacob-grahn** [comment]
Hmm, let me think on this one for a bit. If we do take this out, I'd like to replace it with something that helps the average-joe-not-simmer get a reasonable amount of exp, too.

**Comment by woodenstix** [comment]
@jacob-grahn increased exp drops in campaign maps depending with how many people you're racing with

**Comment by Jmarroqu** [comment]
The members of Gods of Glory were talking about a way for you can make it fair for racer and we had an idea @jacob-grahn I hope you like it; Maybe all Campaign maps should have a bonus exp for every defeated player they beat for example If you win 1st in a campaign map you'll get the exp you'll get + 150 exp then 2nd place would get +100, 3rd would get 50 and last place would get 5 or 10 exp and in return the +0 exp is gone.

**Comment by VipaPR2** [comment]
That's actually a pretty good idea @Jmarroqu

**Comment by LP-PR2** [comment]
I like @Jmarroqu 's idea, but I thought of something else that could benefit the campaign racers, and that's to increase the amount of exp you earn for winning duplicated parts, as nowadays 5 exp will not benefit anyone for anything, as you need 4 players to earn the parts, i think 50-100 exp for winning the part seems a lot more reasonable.

**Comment by woodenstix** [comment]
remember playing PR3 in 2012? Sim maps didn't work, because you would get 0 exp from it (you didn't move).

**Comment by jacob-grahn** [comment]
Thanks fourst4r, I went ahead and merged this in. We'll work on giving racers more exp next!

**Pull request merged**
