### PR TITLE
Add top left corner menu

### PR DESCRIPTION
**Pull request by Altex1**
New menu for pr2hub with the missing page links.

Preview of the background change feature in it:
https://gyazo.com/c2ad9c34db7adf901edb3cde93762a8d

### CODE REVIEW

**Comment by bls1999** [comment]
Good pull!  I have some changes I'm going to submit to your repo, but overall this is really really great.

One question: is the menu button stationary at the top of the page, or does it move with the scrolling?

**Comment by jacob-grahn** [comment]
The background changer is cool, but I wonder if it introduces any security problems.

**Comment by Altex1** [comment]
@jacob-grahn It doesn't cause any security risks because the change happens clientside, even if someone entered malicious image to it, then it would only run on their browser and no one else would get affected.

**Comment by jacob-grahn** [comment]
Hey @Altex1, this is really cool! I think adding javascript to this simple page is a bit of overkill though.

**Pull request closed without merging**
