### PR TITLE
100k is too high of a max

### PR DESCRIPTION
**Pull request by famelegend1**
55k should be fair

### CODE REVIEW

**Comment by bls1999** [comment]
100K is fine IMO. @aaaaaa123456789?

**Comment by aaaaaa123456789** [comment]
It's a safeguard, it's OK

**Comment by bls1999** [comment]
@aaaaaa123456789 100K or 55K? Sorry lol

**Comment by aaaaaa123456789** [comment]
100k. It should be an impossible value.

**Comment by EternalUF** [comment]
Doesn't Arti give VERY close to this amount depending on your rank? @famelegend1

**Comment by famelegend1** [comment]
55k gives a few thousand exp of leeway.

**Comment by bls1999** [comment]
I'm gonna say this isn't needed.  There are necessary checks and then there are unnecessary checks.  100K suffices.

**Comment by famelegend1** [comment]
im determined to put a halt to all forms of botting... but okay.

**Pull request closed without merging**
