### PR TITLE
Fix FAH pt. 79

### PR DESCRIPTION
**Pull request by bls1999**
Oh, you know. Folding at Home decided to update their fast teampage URL for the first time since PR2 came out, so it broke yet again.

I'd like to be able to go a year without this breaking, even if it's not my fault in the first place. That would be nice.

### CODE REVIEW

**Comment by famelegend1** [comment]
LOL

**Comment by bls1999** [comment]
Oof, wrong button.

**Comment by jacob-grahn** [comment]
Nôöòóøōõ

Well, thanks for fixing it!

**Comment by bls1999** [comment]
Sure thing @jacob-grahn!

**Pull request merged**
