### PR TITLE
htmlspecialchars -> ENT_QUOTES, various small edits

### PR DESCRIPTION
**Pull request by bls1999**
`htmlspecialchars($variable, ENT_QUOTES);`

Adds the ENT_QUOTES flag to all instances of htmlspecialchars.

In addition to this change, this pull also:
 - Converts `forgot_password.php` to use the `send_email` function
 - Fixes an issue with third-party data called in `ip_info.php` not displaying properly
 - Fixes a small grammatical error in `/multiplayer_server/fns/client/moderation.php`
 - Adds F@H guide to the guides command (credit to ZXD for [this idea](https://jiggmin2.com/forums/showthread.php?tid=1284))
 - Fixes an issue with warns/kicks being able to be administered by temps to anyone
 - Fixes variable in admins' `/debug` command
 - Fixes/automates bunny set (easter) awarding code and moves operation from `login.php` to `data_fns.php`

Travis status: [Build Status](https://travis-ci.org/jacob-grahn/platform-racing-2-server/builds/458665527)

### CODE REVIEW

**Comment by Stxtics** [comment]
Add https://pr2hub.com/contests to /guides also?

**Comment by bls1999** [comment]
@Stxtics That link isn't really a guide, so that's why I originally excluded it. I'd actually be in favor of a separate chat command for contests, since they're a pretty large subject.

**Comment by bls1999** [comment]
(Travis: [Build Status](https://travis-ci.org/jacob-grahn/platform-racing-2-server/builds/452743615))

**Comment by EternalUF** [comment]
Yes <3

**Comment by jacob-grahn** [comment]
:+1:

**Pull request merged**
