### PR TITLE
Create guild_search.php

### PR DESCRIPTION
**Pull request by BrokenBulb78**
Guild search page is finally ready! ^^

@jacob-grahn don't merge this yet until @bls1999 says it's ready to be merged. He has to check my code for errors 😄

### CODE REVIEW

**Comment by bls1999** [comment]
I have some changes to make that I'll submit to your repo in a few hours.  Overall, good pull!

**Comment by BrokenBulb78** [comment]
Thank ya! :3

**Comment by BrokenBulb78** [comment]
@jacob-grahn now the pull is ready.

**Comment by bls1999** [comment]
@BrokenBulb78 real quick, I made one mistake.  Remove line 5 in guild_search.php and it should be good to go.

**Comment by BrokenBulb78** [comment]
Done. 👍

**Comment by jacob-grahn** [comment]
:+1:

**Pull request merged**
