### PR TITLE
Create Level Leaderboard

### PR DESCRIPTION
**Pull request by Stxtics**
First time programming in PHP so there may be some small errors or little things that can be improved.

Basically this is like leaderboard.php but for levels.

I used leaderboard.php as a guide and just made modifications where necessary.

As of now, it selects levels with more than 20000 plays. 

That may be a little low so I'm happy for it to be increased if needed. 

I was thinking about making it select only published levels but I don't see much harm with it not.

### CODE REVIEW

**Comment by bls1999** [comment]
Nice idea! I'll take a look when I get a chance. 🦃

**Comment by bls1999** [comment]
Hey Matt, I finally got a chance to look at this.

First of all, nice pull! I like the concept.

Here's the only error I got when I put it all together.
 - levels.php, L544: syntax error, unexpected ',', expecting variable (T_VARIABLE)

There was a technical note I had:
 - level_leaderboard.php, L59 & L64: the properties `name` for username and `power` for user group doesn't exist in the `levels` table. You'd need to use `user_select_name_and_power($pdo, $level->user_id)` to get those values instead.

I had a few ideas, including how to possibly limit server load from this a little bit.
 - What if we pull directly from the ATB list instead of retrieving from the database each time (see hint.php)? That seems like it would be a good method of using cached levels and keeping consistency across platforms (e.g. ATB, level leaderboard, etc).
 - I like the concept of linking to the level, but I think just linking to the text file might be a little awkward. I'd want to implement some kind of level information page for this. I made one... *wayyyyy* back in the day... just because?? that *might* still work, depending on if things have really changed at all. I warn you, no one has seen this code since 12 Feb 2018... not even me...

```php
<?php

require_once("../fns/all_fns.php");
require_once("../fns/output_fns.php");

output_header('Level Info');

try {

	//connect
	$db = new DB();

} catch (Exception $e) {
	echo 'Error: ' . $e->getMessage();
	output_footer();
	die();
}

// get the user input
$level_id = (int) $_GET['level_id'];

// get and parse the data
$file = file_get_contents('https://pr2hub.com/levels/'.$level_id.'.txt');
parse_str($file, $data);

// these will always be present
// all of these will be integer values
$level_id = (int) $data['level_id']; // done
$max_time = (int) $data['max_time']; // done
$min_rank = (int) $data['min_level']; // done
$published = (int) $data['live']; // done
$save_time = (int) $data['time']; // done
$user_id = (int) $data['user_id']; // done
// these either have potential to be or are definitely something other than integers
$gravity = $data['gravity']; // done
$items = $data['items'];
$song = $data['song']; // done
$safe_title = htmlspecialchars(urldecode($data['title'])); // done
$safe_note = htmlspecialchars(urldecode($data['note'])); // done

// get the creator information
$user = $db->grab_row('user_select', array($user_id));
if (!$user) {
	$safe_user_name = "User ID #$user_id";
}
else {
	$safe_user_name = htmlspecialchars($user->name);
}

// creator group
$group = $user->power;

switch($group) {
	case 0:
		$group_name = "Guest";
		$group_color = "#7E7F7F";
		break;
	case 1:
		$group_name = "Member";
		$group_color = "#047B7B";
		break;
	case 2:
		$group_name = "Moderator";
		$group_color = "#1C369F";
		break;
	case 3:
		$group_name = "Admin";
		$group_color = "#870A6F";
		break;
	default:
		$group_name = "Unknown";
		$group_color = "#000000";
		break;
}

/* the variables below are a little more complicated...
let's try to get them; if they don't work, it isn't the end of the world */

// check game mode
if(array_key_exists('gameMode', $data) && strlen(trim($data['gameMode'])) !== 0) {
	$mode = $data['gameMode'];
	
	switch ($mode) {
		case 'race':
			$mode = "Race";
			break;
		case 'deathmatch':
			$mode = "Deathmatch";
			break;
		case 'egg':
			$mode = "Alien Eggs";
			break;
		case 'objective':
			$mode = "Objective";
			break;
		default:
			$mode = "Race";
			break;
	}
}
else {
	$mode = 'Race';
}

// chance of cowboy mode
if(array_key_exists('cowboyChance', $data) && strlen(trim($data['cowboyChance'])) !== 0) {
	$cowboy_chance = $data['cowboyChance'];
}
else {
	$cowboy_chance = (int) 5;
}

// password protected?
if(array_key_exists('has_pass', $data) && strlen(trim($data['has_pass'])) !== 0) {
	$has_pass = (int) $data['has_pass'];
}
else {
	$has_pass = (int) 0;
}

// version number
if(array_key_exists('version', $data) && strlen(trim($data['version'])) !== 0) {
	$version = $data['version'];
}
else {
	$version = 1;
}

// gravity check
if(!array_key_exists('gravity', $data) || strlen(trim($data['gravity'])) === 0 || $data['gravity'] == ('1.0' || '1') || (int) $data['gravity'] === 1) {
	$gravity = "Normal (1.0)";
}
else {
	$gravity = (int) $data['gravity'];
}

// song switch
switch ($song) {
	case 0:
		$song_name = "None";
		break;
	case 1:
		$song_name = "Miniature Fantasy - Dreamscaper";
		break;
	case 2:
		$song_name = "Under Fire - Andrew Parker";
		break;
	case 3:
		$song_name = "Paradise on E - API";
		break;
	case 4:
		$song_name = "Crying Soul - Bounc3";
		break;
	case 5:
		$song_name = "My Vision - David Orr";
		break;
	case 6:
		$song_name = "Switchblade - SKAzini";
		break;
	case 7:
		$song_name = "The Wires - Cheez-R-Us";
		break;
	case 8:
		$song_name = "Before Mydnite - F-777";
		break;
	case 9:
		$song_name = "Desert Rose - Metalcan";
		break;
	case 10:
		$song_name = "Broked It - SWiTCH";
		break;
	case 11:
		$song_name = "Hello? - TMM43";
		break;
	case 12:
		$song_name = "Pyrokinesis - Sean Tucker";
		break;
	case 13:
		$song_name = "Flowerz 'n' Herbz - Brunzolaitis";
		break;
	case 14:
		$song_name = "Instrumental #4 - Reasoner";
		break;
	case 15:
		$song_name = "Prismatic - Lunanova";
		break;
	case 16:
		$song_name = "We Are Loud";
		break;
	default:
		$song_name = "Random";
		break;
}

// items
try {

	// make an array and some corresponding variables
	$items_int = (int) $items;
	$item_array = explode("`", $items);
	$first_key = $item_array[0];
	$first_key_int = (int) $item_array[0];
	$item_array_highest_num = max(array_keys($item_array));
	$item_count = count(array_keys($item_array));
	
	// start the string
	$item_string = "";
	
	// define item numbers
	$item_1 = "Laser Gun";
	$item_2 = "Mine";
	$item_3 = "Lightning";
	$item_4 = "Teleport";
	$item_5 = "Super Jump";
	$item_6 = "Jet Pack";
	$item_7 = "Speed Burst";
	$item_8 = "Sword";
	$item_9 = "Ice Wave";
	
	// all or nothing
	$all = "All";
	$none = "None";
	
	// what separates the items
	$sep = ", ";
	
	// if there are nine items, echo all
	if ($item_count === 9) {
		throw new Exception($all);
	}
	
	// if there is one array item and it's empty
	if (!isset($items) || ($item_count === 1 && empty($items))) {
		throw new Exception($none);
	}
	
	if ($first_key_int !== 0) {
	
		// if the first item in the array is not 0 and is not empty
		if (!empty($first_key)) {
		
			foreach(range(0,$item_array_highest_num) as $arr_num) {
				
				// get the number returned by the game
				$current_item = $item_array[$arr_num];
				
				// if it isn't the first item in the array, append ", item" to the string
				if ($arr_num !== 0) {
					$item_string .= $sep.${"item_".$current_item};
					continue;
				}
				// if it is the first item in the array, start with the item
				else {
					$item_string = ${"item_".$current_item};
					continue;
				}
			}
			
			// if all items but ice wave are enabled, echo "All, except Ice Wave"
			if (strpos($item_string, "Laser Gun") !== false &&
			strpos($item_string, "Mine") !== false &&
			strpos($item_string, "Lightning") !== false &&
			strpos($item_string, "Teleport") !== false &&
			strpos($item_string, "Super Jump") !== false &&
			strpos($item_string, "Jet Pack") !== false &&
			strpos($item_string, "Speed Burst") !== false &&
			strpos($item_string, "Sword") !== false &&
			strpos($item_string, "Ice Wave") === false) {
				$item_string = "All, except Ice Wave";
				throw new Exception($item_string);
			}
			
			throw new Exception($item_string);

		}
	}
	else {
		
		// for each array key number, search for the literal name of the item
		foreach(range(0,$item_array_highest_num) as $arr_num) {
		
			if (strpos($item_array[$arr_num], "Laser Gun") !== false) {
				$item_string .= $item_1.$sep;
				continue;
			}
			else if (strpos($item_array[$arr_num], "Mine") !== false) {
				$item_string .= $item_2.$sep;
				continue;
			}
			else if (strpos($item_array[$arr_num], "Lightning") !== false) {
				$item_string .= $item_3.$sep;
				continue;
			}
			else if (strpos($item_array[$arr_num], "Teleport") !== false) {
				$item_string .= $item_4.$sep;
				continue;
			}
			else if (strpos($item_array[$arr_num], "Super Jump") !== false) {
				$item_string .= $item_5.$sep;
				continue;
			}
			else if (strpos($item_array[$arr_num], "Jet Pack") !== false) {
				$item_string .= $item_6.$sep;
				continue;
			}
			else if (strpos($item_array[$arr_num], "Speed Burst") !== false) {
				$item_string .= $item_7.$sep;
				continue;
			}
			else if (strpos($item_array[$arr_num], "Sword") !== false) {
				$item_string .= $item_8.$sep;
				continue;
			}
			else if (strpos($item_array[$arr_num], "Ice Wave") !== false) {
				$item_string .= $item_9.$sep;
				continue;
			}
			
		}
		
		// if all items but ice wave are enabled, echo "All, except Ice Wave"
		if (strpos($item_string, "Laser Gun") !== false &&
		strpos($item_string, "Mine") !== false &&
		strpos($item_string, "Lightning") !== false &&
		strpos($item_string, "Teleport") !== false &&
		strpos($item_string, "Super Jump") !== false &&
		strpos($item_string, "Jet Pack") !== false &&
		strpos($item_string, "Speed Burst") !== false &&
		strpos($item_string, "Sword") !== false &&
		strpos($item_string, "Ice Wave") === false) {
			$item_string = "All, except Ice Wave";
			throw new Exception($item_string);
		}
		
		// remove last $sep, send it to catch (which defines $disp_items)
		$item_string = substr($item_string, 0, -2);
		throw new Exception($item_string);
			
	}
}
catch (Exception $e) {
	$disp_items = $e->getMessage();
}

// do things with the variables
$is_published = check_value($published, 1, 'Yes', 'No');
$has_password = check_value($has_pass, 1, 'Yes', 'No');
$save_time = date('l, F j, Y \a\t H:i:s T', $save_time);

// min rank
if ($min_rank === 0) {
	$min_rank = "None";
}

// max time variables
$hours = gmdate('G', $max_time);
$minutes = gmdate('i', $max_time);
$int_mins = (int) $minutes;
$seconds = gmdate('s', $max_time);
if ($int_mins < 10 && $hours < 1) {
	$minutes = $int_mins;
}

// build the max time output
if ($max_time === 0) {
	$max_time = "Infinite";
}
if ($max_time != 'Infinite') {
	$time_str = "";
	if ($hours > 0) {
		$time_str .= "$hours:";
	}
	$time_str .= "$minutes:$seconds";
	$max_time = $time_str;
}

/* ----- Time to start the visible part of the page... ----- */

// pretty things
echo '<center><font face="Gwibble" class="gwibble">-- Level Info --</font></center><br><br>';

// level ID form
echo "<form method='get' action='level_info.php'>";
echo "Level ID: <input type='text' name='level_id' value='$level_id'>&nbsp;";
echo "<input type='submit' value='Go'></form><br>";

// level info
$urlencode_username = urlencode($safe_user_name);
echo "Level: <b>$safe_title</b> by <b><a href='//pr2hub.com/player_search.php?name=$urlencode_username'><span style='color: $group_color; text-decoration: underline;'>$safe_user_name</span></a></b><br><br>";
echo "Last Edited: $save_time<br>";
echo "Version: $version<br>";
echo "Published? $is_published<br>";
echo "Password Protected? $has_password<br>";
if ($min_rank != 'None') {
	echo "Minimum Rank Requirement: $min_rank<br>";
}
echo "Level Time: $max_time<br>";
echo "Gravity: $gravity<br>";
echo "Song: $song_name<br>";
echo "Items: $disp_items<br>";
if (!is_empty($safe_note)) {
	echo "Description: <i>$safe_note</i><br>";
}

output_footer();
```

**Comment by Stxtics** [comment]
> level_leaderboard.php, L59 & L64: the properties name for username and power for user group doesn't exist in the levels table. You'd need to use user_select_name_and_power($pdo, $level->user_id) to get those values instead.

Oh okay, I thought that would be ok as I am selecting them in the query in the levels.php file.

So what exactly is returned then from the query that I made?

> Small one: maybe have the level title and creator's name in separate columns?

I don't think this would have much of an effect on the server load unless I'm wrong. I was thinking about having it that way but thought I'd put them in the format of the hint.

> What if we pull directly from the ATB list instead of retrieving from the database each time (see hint.php)? That seems like it would be a good method of using cached levels and keeping consistency across platforms (e.g. ATB, level leaderboard, etc). It really comes down to how you want to sort the leaderboard.

My intention for this was to be different to all-time best which is why I made the query select levels in order of play count, rather than how all-time best works. 

We could always make an all-time-best.php ;) and maybe others, but I don't see much of a need for it. I already implemented a feature for Fred where you can view campaign/all-time best/today's best/newest pages. It looks like this.
image

> I like the concept of linking to the level, but I think just linking to the text file might be a little awkward. I'd want to implement some kind of level information page for this. I made one... wayyyyy back in the day... just because?? that might still work, depending on if things have really changed at all. I warn you, no one has seen this code since 12 Feb 2018... not even me...

Yeah, that would be great, I didn't like it linking to the text file either so a page like that would be great. I'd be happy to work on all this stuff mentioned above but I don't know how I can test my changes to make sure they work. What program(s) would you recommend? You can DM on Discord too if you want as I don't get notifications for Github responses and don't always check daily.

**Comment by bls1999** [comment]
> Oh okay, I thought that would be ok as I am selecting them in the query in the levels.php file.
> 
> So what exactly is returned then from the query that I made?

I haven't tested, but I believe it would throw an error. Instead, you'd want something like this:

```sql
SELECT
  l.level_id,
  l.title,
  l.play_count,
  u.user_id,
  u.name,
  u.power
FROM
  levels l
LEFT JOIN
  users u ON l.user_id = u.user_id
WHERE
  l.play_count > 20000
ORDER BY
  l.play_count DESC
LIMIT
  :start, :count
```
That returns the following:

```
+----------+--------------------------------------+------------+---------+------------------+-------+
| level_id | title                                | play_count | user_id | name             | power |
+----------+--------------------------------------+------------+---------+------------------+-------+
|  4866546 | Volcanic Inferno                     |  337269849 | 3789429 | Pounce           |     1 |
|  3236908 | The Golden Compass                   |   54324793 |  316273 | -Shadowfax-      |     1 |
|  5793214 | Redemption                           |   41207399 |   32949 | cooldude90       |     1 |
|  1896157 | -Deliverance-                        |   29837840 | 1131779 | changelings      |     1 |
|    84156 | Hat Factory                          |   26486362 |       1 | Jiggmin          |     3 |
|    50815 | Newbieland 2                         |   12487175 |       1 | Jiggmin          |     3 |
|  5877893 | Apocalypse                           |   12117162 | 4635393 | Divinity         |     1 |
|    80814 | Mario Bros remix  v.1.3(time attack) |   10356424 |    7563 | zerostar(oO)     |     1 |
|   102573 | razor blade                          |    9533713 |    7563 | zerostar(oO)     |     1 |
|     7376 | Soul Temple                          |    9388971 |    8023 | julls            |     1 |
|    76127 | Zerostar(Â¬Â¬)                       |    9346405 |    7563 | zerostar(oO)     |     1 |
|    81998 | Its New York!                        |    9142459 |    2166 | Stevedx20        |     1 |
|   798121 | The Legend                           |    8092255 |   32641 | nerdy            |     1 |
|  3460484 | Candyland                            |    4797465 |   17275 | Albatross        |     1 |
|    67098 | Candyland Campaign                   |    4676137 |   17275 | Albatross        |     1 |
|  4925543 | Newby Train                          |    4337238 |  174326 | jessica rocks    |     1 |
|  6382281 | Christmas                            |    4274127 |  254915 | TRUC             |     1 |
|   728037 | Urban race                           |    3252315 |  608359 | Mf Eclipse       |     1 |
|  1990682 | Blacklight                           |    3095623 |    7475 | TheGrizz         |     1 |
|  4976738 | Mario Bros Speed                     |    2506271 |    7563 | zerostar(oO)     |     1 |
|  6376626 | Portal Temple                        |    1851775 | 4450115 | justinbob100     |     1 |
|  3711604 | Lightspeed 2                         |    1830200 | 1995055 | mapleleaf        |     1 |
|  5858000 | ~Cavernous~                          |    1687102 | 4450115 | justinbob100     |     1 |
|  1442589 | Mf's, Fantasy Race                   |    1636331 | 1132131 | Mfs finest       |     1 |
|  1732415 | Macro Sim Perfect                    |    1445799 | 1246432 | Xp SIm Machine   |     1 |
|  1973213 | Sim Perfection                       |    1229565 |  991923 | luis16           |     1 |
|  5738275 | First Frontier                       |    1192346 | 1882652 | Twilan           |     1 |
|  5821108 | Smog                                 |    1112261 | 4917612 | Kwing            |     1 |
|  5819999 | Chromium                             |    1024888 | 3483109 | xXsuper3Xx       |     1 |
|  5749152 | Malfunction                          |     987337 | 1602346 | ptk94            |     1 |
|  4867167 | Speed Meadow                         |     941483 | 1892185 | Neomonster       |     1 |
|  1131125 | Storm                                |     880265 |  386423 | PooZy            |     1 |
|  1941548 | Pr3's Randomness                     |     741616 | 1468938 | Pr3 Kings        |     1 |
|  4413878 | Sim Perfection Artless               |     716185 |  991923 | luis16           |     1 |
|  5960781 | Journey to Fred                      |     695471 | 5229652 | RidePonyRide     |     1 |
|  2020043 | Faked                                |     639725 | 1468938 | Pr3 Kings        |     1 |
|  3284433 | Classic Traps                        |     639172 | 2442785 | Devious Shadows  |     1 |
|  1009508 | In Progress                          |     621784 |  744351 | verados          |     1 |
|  2980090 | Sim Perfection 4.                    |     620799 |  991923 | luis16           |     1 |
|  3284352 | RvsB, a Colonel's Sacrifice          |     619900 |  608359 | Mf Eclipse       |     1 |
|  5804191 | Luna Temple V3                       |     594075 |  925095 | Overbeing        |     1 |
|  3564605 | How to make a Hat Machine            |     544092 | 1995055 | mapleleaf        |     1 |
|  1583507 | R vs B, Showdown                     |     498709 | 1132131 | Mfs finest       |     1 |
|  3480351 | Space Station                        |     475975 | 1995055 | mapleleaf        |     1 |
|  6454109 | C-Sim 54                             |     470375 | 5601846 | Sim#             |     1 |
|  2247712 | Exp Sim - X5 Bonus                   |     460605 |  484684 | quesin           |     1 |
|  5826156 | Cretaceous Race                      |     433939 | 4591711 | Mkl              |     1 |
|  1840191 | Macro Sim Perfect V2                 |     415866 | 1246432 | Xp SIm Machine   |     1 |
|  5919018 | Deathmatch..                         |     414827 | 3950195 | THEFASTESTOFALL  |     1 |
|  5251606 | Blacklight 2                         |     398276 | 3718968 | a7x3             |     1 |
|  6447419 | Object Sim 85                        |     396019 | 5459608 | ?                |     1 |
|  5336563 | Art Gallery                          |     387573 | 3483109 | xXsuper3Xx       |     1 |
|  3248159 | Spark of War                         |     380708 |  608359 | Mf Eclipse       |     1 |
|   170118 | Jail Break                           |     378930 |   36754 | The Racer        |     1 |
|  1995745 | Marco Sim Perfect                    |     376716 |  613459 | LamLam           |     1 |
|  2595827 | Sim Perfection 3                     |     374385 |  991923 | luis16           |     1 |
|  5830113 | The Stone Age                        |     360471 | 1724565 | Shadow Z         |     1 |
|  1317626 | R VS B, Final Frontier               |     338973 |  234385 | Mfdom            |     1 |
|  3556850 | Pro Sim                              |     333355 | 3541998 | Chris5a5         |     1 |
|  2139164 | Sim Perfection 2                     |     333067 |  991923 | luis16           |     1 |
|  6487011 | Exp Sim                              |     320839 | 1526406 | K0NR4D           |     1 |
|  2933592 | {4P} Trapwork                        |     320551 | 2442785 | Devious Shadows  |     1 |
|  3779718 | Animation 2                          |     320496 | 1095631 | n man292         |     1 |
|  3736069 | RvsB, A New Hope                     |     284247 |  234385 | Mfdom            |     1 |
|  5760134 | 3301                                 |     280257 |  234385 | Mfdom            |     1 |
|  1609773 | Wasteland                            |     279929 |  386423 | PooZy            |     1 |
|  6454775 | C-Sim 54                             |     271228 | 1168774 | U                |     1 |
|  5765933 | Evacuation                           |     266512 | 4887063 | Subteap          |     1 |
|   712373 | Oh Deary Me                          |     266503 |  501182 | EpicFailGuy();   |     1 |
|   563130 | Questions II                         |     256396 |   15145 | Red Jackdaw      |     1 |
|   638355 | Bowser's revenge *                   |     252836 |  234385 | Mfdom            |     1 |
|  1527804 | Questions IV                         |     240181 |   15145 | Red Jackdaw      |     1 |
|   744582 | Power Leveling                       |     236865 |  216955 | intrpd           |     1 |
|   208732 | Questions...                         |     235281 |   15145 | Red Jackdaw      |     1 |
|  6484979 | Obj Macro                            |     223823 | 1184033 | x2               |     1 |
|  5788241 | Solar Flare                          |     219650 |  476412 | dealth           |     1 |
|  6483402 | Obj Macro                            |     213938 | 5492435 | Back Pack        |     1 |
|  3342097 | Animation =)                         |     212516 |  498930 | Vojife           |     1 |
|  5846986 | Gold Rush                            |     207628 | 4591711 | Mkl              |     1 |
|  5856207 | -Flummox-                            |     201040 | 4528001 | ~Light2Shine~    |     1 |
|  2474450 | mooky 01                             |     193913 | 1937319 | LewisClark       |     1 |
|  1536580 | Special Effects II                   |     193048 |  846562 | Fire Shadow      |     1 |
|  6492131 | SimHigh                              |     192867 | 5636539 | NL0              |     1 |
|  2994463 | Macro Perfect                        |     192682 |    5089 | PLAYA 1          |     1 |
|  6048640 | The Islands In The Sky               |     190210 | 3837909 | SouthWind        |     1 |
|  3125567 | Art Questions                        |     181670 | 1673496 | darth vadar      |     1 |
|  5798302 | Airox                                |     177752 | 3483109 | xXsuper3Xx       |     1 |
|  6380818 | Snowy Starter                        |     176889 | 5439971 | Dexterity        |     1 |
|   150106 | abandon ship                         |     176033 |   70838 | golioth hog      |     1 |
|  3455216 | Trapwork 2                           |     175098 | 2442785 | Devious Shadows  |     1 |
|   364548 | Big Bang                             |     173435 |   23069 | darthjavo        |     1 |
|  6055651 | Mount Magma                          |     172811 | 5289134 | 5uperTrinity     |     1 |
|  1196120 | PR3                                  |     171324 |   23069 | darthjavo        |     1 |
|  3577946 | ~200 traps~                          |     167554 | 3762206 | Devious Dragon   |     1 |
|  6483560 | [4p] EXP Sim/Macro Machine           |     167144 | 1188616 | Magic            |     1 |
|  4799190 | Sim Perfection Artless 1             |     164742 | 4486071 | Patrolik.        |     1 |
|  6493794 | Jungle Secrets v2.5                  |     164501 | 5187899 | 81352752C86227B8 |     1 |
|  4964814 | Newbieland 3*                        |     162116 | 1689289 | animorphs        |     1 |
|   665299 | Perilous Plunge                      |     160184 |  450094 | darktoaster      |     1 |
|  1754408 | DonÂ´t Move 1 Player IV.             |     159576 |  991923 | luis16           |     1 |
+----------+--------------------------------------+------------+---------+------------------+-------+
```

You might consider removing campaign levels from the level leaderboard, as a lot of the play counts are inflated due to botting (especially volcanic inferno... :eyes:).

> I don't think this would have much of an effect on the server load unless I'm wrong. I was thinking about having it that way but thought I'd put them in the format of the hint.

That's fine. It wasn't so much a suggestion for saving server load as it was for display.

> My intention for this was to be different to all-time best which is why I made the query select levels in order of play count, rather than how all-time best works.
> 
> We could always make an all-time-best.php ;) and maybe others, but I don't see much of a need for it. I already implemented a feature for Fred where you can view campaign/all-time best/today's best/newest pages. It looks like this. -snip-

Gotcha. So I think the way to do this would be to generate a master list on an interval (probably daily, since I don't see this updating so often that we need to pull data any more frequently than that) and throw it in a file like the other lists.

> Yeah, that would be great, I didn't like it linking to the text file either so a page like that would be great. I'd be happy to work on all this stuff mentioned above but I don't know how I can test my changes to make sure they work. What program(s) would you recommend? You can DM on Discord too if you want as I don't get notifications for Github responses and don't always check daily.

I'll let you know there, then!

**Comment by Stxtics** [comment]
Sorry but I feel like I'm never going to get to this, it would involve me learning a new language when I'm currently working on other things *wink wink*.

I'll let you decide whether to close this or leave it open, but I think there isn't much of a need for this stuff apart from maybe the level leaderboard but you can decide.

**Comment by bls1999** [comment]
No worries! I didn't really have a plan to implement this either, as I too am working on bigger and more exciting things. ;)

**Pull request closed without merging**
