### PR TITLE
Make server owners admins on their server, add become_guest()

### PR DESCRIPTION
**Pull request by bls1999**
- Server owners are now server admins and can promote temp mods on their server
 - Testing the new `become_guest()` function I added to Player.php for badges support on Kong (only one account is enabled to use this function on login)
 - Make HH on server restart 30 mins and a 1/10 chance of occurring
 - Add /rules command and change the welcome message for main chat to include the rules link

### CODE REVIEW

**Comment by LP-PR2** [comment]
"Make HH on server restart 30 mins and a 1/10 chance of occurring"

When were the HHs an issue?

**Comment by fourst4r** [comment]
> Make HH on server restart 30 mins and a 1/10 chance of occurring

...why?

I always thought of the happy _hour_ during server restart as like a consolation for the inconvenience of having your game interrupted.

Now you propose we have a 1 in 10 chance to get _half_ of an HH? This is an over-complicated fix for an issue that doesn't exist.

**Comment by LP-PR2** [comment]
"Theoretically, one server will get a 30-min happy hour at the daily server restarts"

That's not a happy hour, and what if that one server is a private server? Because those exist too.

**Comment by bls1999** [comment]
The idea is that instead of all of the servers getting spammed with full Happy Hours once a day, the occurrence is random but the chance is way higher.  I would be fine with making the time 60 minutes again, although the thought there was to have sort of a mini Happy Hour for a server restart instead of a full one.

**Comment by LP-PR2** [comment]
@bls1999 why not make it a certain hh on 1 server? That way it's not spamming all the servers and it's guaranteed to be on a public server and not a guild server.

**Comment by bls1999** [comment]
Sounds good to me.

**Comment by bls1999** [comment]
I put it on Carina ^^

**Pull request merged**
