### PR TITLE
Prevent forcing log out

### PR DESCRIPTION
**Pull request by Myst1cZ**
Fix to prevent automatic log out through things such as image or web page.

### CODE REVIEW

**Comment by bls1999** [comment]
The reason I didn't do this is because some clients are embedded on different sites other than what is allowed.  It doesn't make sense not to allow logouts from everywhere.

**Comment by bls1999** [comment]
Also, it's not a big deal if you get logged out.  That can't cause any lasting harm; it's only a mild annoyance.

**Comment by jacob-grahn** [comment]
Yeah, I don't think this one would work

**Comment by jacob-grahn** [comment]
What if we store the referrer in the cookie when it's created, and then ignore the cookie if it gets sent from a different referrer?

**Comment by Myst1cZ** [comment]
@jacob-grahn Not sure if that would be enough since PHP setcookie or javascript document.cookie could be used to set the referrer in cookie before sending request.

**Pull request closed without merging**
