### PR TITLE
Add time left command in Player.php

### PR DESCRIPTION
**Pull request by Stxtics**
This is a command for owners of Private Servers. When they type /timeleft or /ps it will tell them when their private server will expire (I think). This is my first ever time doing something in php but I believe this should not cause any errors. The only issue I think that could occur is how this expire time might be shown. From what I've seen I think it is in a date format but I am not 100% sure. Anyone can modify this if they want but if you can tell me why you are changing what you did that will help. Thanks!

### CODE REVIEW

**Comment by bls1999** [comment]
@Stxtics since I am submitting a change to Player.php, let me add this to my pull so Jiggmin doesn't have to fix the merge conflicts.

**Comment by Stxtics** [comment]
@bls1999 do I have to like allow you to do that or will it let you?

**Comment by bls1999** [comment]
I'm just going to add it manually to my pull because that seems like the easier course of action.

**Comment by bls1999** [comment]
Did it https://github.com/bls1999/platform-racing-2-server/blob/patch-1/multiplayer_server/Player.php

**Pull request closed without merging**
