### PR TITLE
Update delete_old_accounts.php

### PR DESCRIPTION
**Pull request by VipaPR2**
Not entirely sure if this is a viable method to fix "userId: null" users not being deleted even though they meet the requirements for deletion however I'm fairly positive it should work. I also wanted to inquire as to how often this script is executed, would it be possible for you to re-run the script after adding these fixes?

### CODE REVIEW

**Comment by VipaPR2** [comment]
Any idea if it's possible to make it work in any way?

**Comment by bls1999** [comment]
I'd need to know the queries sent to the database

**Comment by VipaPR2** [comment]
Alright, Jiggmin will see this thread and he can maybe fix it.

**Comment by bls1999** [comment]
The issue is that the pr2_insert procedure isn't called when a user registers, it's called when a user logs in for the first time.  I think in order for the script to determine user ID, it goes through pr2_select instead of user_select.  If this is the case, it could be theoretically be fixed by going through user_select instead.

**Comment by jacob-grahn** [comment]
@VipaPR2 could you open this as an issue? I think the solution @bls1999 suggested would probably work.

**Pull request closed without merging**
