### PR TITLE
Added 100 character check in Player.php

### PR DESCRIPTION
**Pull request by BrokenBulb78**
This is useful because anyone can modify the client and increase the max character value.

### CODE REVIEW

**Comment by EternalUF** [comment]
When you do this, by highlighting and typing a number in the stats. Does it actually stick? I never believed it did.

**Comment by Antonhs30000** [comment]
Do you mean this? 
image

**Comment by EternalUF** [comment]
Yes, as seen as you switch tabs it reverts, correct?

**Comment by woodenstix** [comment]
You clearly don't understand simple questions, @Antonhs30000 ...

**Comment by Antonhs30000** [comment]
It set the stat you typed @EternalUF

**Comment by EternalUF** [comment]
https://i.imgur.com/O3Lngfc.gifv

Here's the 10 second test you've requested @woodenstix

**Comment by Antonhs30000** [comment]
Ye it reverts, don't worry @EternalUF

**Comment by Antonhs30000** [comment]
Also, why are we talking about the player stats? This pull is for 100 character check in chat message xD

**Comment by EternalUF** [comment]
LOL WUT, I'm deleting all of my comments.

**Comment by Antonhs30000** [comment]
Ye same.

**Comment by Myst1cZ** [comment]
There's missing ")" in the "else if", would cause error.

**Comment by Stxtics** [comment]
@Antonhs30000 https://phpcodechecker.com/

**Comment by Antonhs30000** [comment]
LOL oopsie @Myst1cZ

**Comment by Antonhs30000** [comment]
kk @bls1999 closing it

**Comment by jacob-grahn** [comment]
We could move the check up above the shrug and lenny code.

**Comment by bls1999** [comment]
@BrokenBulb78 I submitted a pull to your repo.

**Comment by jacob-grahn** [comment]
Thanks!

**Pull request merged**
