### PR TITLE
Update for index

### PR DESCRIPTION
**Pull request by Antonhs30000**
Added Artifact hint, fixed links and added _blank, also better css, image for arti: https://i.imgur.com/IsFJdnD.png

### CODE REVIEW

**Comment by bls1999** [comment]
I like this, but I wonder if we can add this to artifact_hint.php instead of putting it on the homepage.

**Comment by Antonhs30000** [comment]
Putting it on the homepage makes it faster. It's also possible to add a reload button or automatically reload the hint after 1 minute using JavaScript.

**Comment by bls1999** [comment]
The point, though, is that not everyone would enjoy having it on the front page. Plus, it's very easy to do /hint in the chat anyway.

**Comment by jacob-grahn** [comment]
Cool idea! I'd be open to having a page at hint.php, and linking to it from the bottom of index.php.

**Comment by Antonhs30000** [comment]
Oh yeah, you're right! Haha @bls1999

**Pull request merged**
