### PR TITLE
Create staff.php

### PR DESCRIPTION
**Pull request by Antonhs30000**
I just coded a staff list for PR2Hub! It'll help confused members. You can also see which staff member is inactive. Special thanks to @Myst1cZ for helping me on creating this great function! :3

### CODE REVIEW

**Comment by bls1999** [comment]
@jacob-grahn Don't merge this.  http_server/fns/output_fns.php doesn't need more functions.  I'll make a pull later that puts the function in staff.php.

**Comment by woodenstix** [comment]
Please please add this! I will know when to log out with my AUTO-DETECT-STAFF-MEMBER.exe

**Comment by Antonhs30000** [comment]
Lol

**Comment by Antonhs30000** [comment]
@bls1999 I can put the function in staff.php, lemme do it

**Pull request closed without merging**
