### PR TITLE
quickly merge this pls

### PR DESCRIPTION
**Pull request by famelegend1**
oops!

### CODE REVIEW

**Comment by famelegend1** [comment]
@bls1999 this is good right? immediately when my pull request was merged i knew something would be wrong here, but i didnt notice earlier. sorry

**Comment by bls1999** [comment]
Give me some time to take a look at this.

**Comment by famelegend1** [comment]
basically i forgot to change the hat bonus values returned in the finished race panel after cleaning up the hat bonus code

**Comment by bls1999** [comment]
@famelegend1 actually, you're right. I thought the `$hat_bonus` variable eventually included the campaign/hh bonuses as well. I'm still not convinced we need this change, though.

**Comment by famelegend1** [comment]
could always revert what i did to hat_bonus, but i thought it made it look more clear. but of course there's this to change and maybe its best not to play with this for now

**Comment by LP-PR2** [comment]
@bls1999 interesting philosophy

**Comment by jacob-grahn** [comment]
:+1:

**Pull request merged**
