### PR TITLE
Removing useless code

### PR DESCRIPTION
**Pull request by woodenstix**

### CODE REVIEW

**Comment by BrokenBulb78** [comment]
@jacob-grahn DON'T MERGE THIS, that's literally removing the fill slot function lol

**Comment by woodenstix** [comment]
It is useless coding so we can remove it. I dont see what is problem antonhs. This is useful change for efficiency and more understandable code.

**Comment by bls1999** [comment]
While you're at it, why don't you delete multiplayer_server/pr2.php? @woodenstix

**Comment by woodenstix** [comment]
Did you read comment above?

**Comment by fourst4r** [comment]
Looks good.

**Comment by bls1999** [comment]
I did @woodenstix.  I'm suggesting removing some more "useless code."  You could also throw in multiplayer_server/loadup.php

**Pull request closed without merging**
