### PR TITLE
Revert is_from_game fix in logout.php

### PR DESCRIPTION
**Pull request by bls1999**
It's throwing an error every time someone logs out.

### CODE REVIEW

**Comment by Dex472** [comment]
@bls1999 What error it throws?

**Comment by bls1999** [comment]
@Dex472 Error: It looks like you're not using PR2 to log out. For security reasons, you may only log out from a PR2 client.

**Comment by Dex472** [comment]
I think i figured out why this happens, will make pull request as soon i get to fixing it.

**Comment by bls1999** [comment]
@Dex472 could you explain?

**Comment by jacob-grahn** [comment]
I'll revert this for now so people can log out until we've got a fix.

**Pull request merged**
