### PR TITLE
Create email search tool for admins

### PR DESCRIPTION
**Pull request by bls1999**
Allows admins to search for users by email address.  Hopefully in the future I'll figure out a way to grab the username from different email changes too.  That way, not only will we be able to search by the current email address, but we'll also be able to search by any address that has ever been associated with an account.

### CODE REVIEW

**Comment by woodenstix** [comment]
yeah yeah BLS! PLEASE GIVE US ABILITY TO FIND PPL BY EMAIL SO I CAN HIJACK THEIR EMAILS AND RECOVER ACCOUNTS YEES!

**Comment by bls1999** [comment]
@woodenstix lol read the first sentence of the pull request

**Comment by woodenstix** [comment]
Yes, yes, give admins more info so that when we get a corrupt admin they can leak everything! Thanks, bls1999!

**Comment by bls1999** [comment]
1. Admins already have the ability to see users' email addresses, which would mean a theoretical corrupt admin could already leak that data.
2. Using your logic, we should not allow mods or admins to see IP addresses or prior bans since they can be leaked.
3. This could be used to help find lost accounts for people.

**Comment by bls1999** [comment]
Also, in the interest of full disclosure, @woodenstix's original message was:

`yeah yeah BLS! PLEASE GIVE US ABILITY TO FIND PPL BY EMAIL SO I CAN HIJACK THEIR EMAILS AND RECOVER ACCOUNTS YEES!`

And my response was:

`Read the first sentence of the pull request`

**Comment by woodenstix** [comment]
Your response didn't even matter, I edited it 15 seconds later. Are you trying that I am somehow wrong by stating a problem? Keep lying.

**Comment by woodenstix** [comment]
Actually I deleted it :/

**Comment by Antonhs30000** [comment]
Well done Ben! Keep the good work! c:

**Comment by bls1999** [comment]
@jacob-grahn this one is also a quick merge, since it doesn't use any db functions

**Comment by jacob-grahn** [comment]
I'm a little bit uneasy about email addresses being accessible in the first place. I never really wanted to add them in, but people needed a password recovery feature...

With the way companies collect everyone's personal info (and then loose it in a data breach), I'd like us to be as much on the other end of the spectrum as possible.

There are valid and good reasons for this pull request, but if it's possible to get by without access to emails I think that would be better.

Anywho. I'm open to discussion if you disagree.

**Comment by EternalUF** [comment]
Hey Jiggmin! The issue currently, which sparked the creation of this pull is it is extremely difficult figuring out the number of accounts an email has associated to it, so when it comes to mass ban evaders or when someone just forgets the accounts they have on their email (given they provide us the email first). I believe in the future bls1999 wants to implement a search by IP, which would also greatly benefit us for similar reasonings, but I believe he stuck with this first since it was quicker to accomplish. The thing is, the things in this pull is already possible, but it would take an extremely long time and highly inefficient clogging the servers with manually requests member by member. This just eases everything. But once again, I’m open to all opinions!

**Pull request merged**
