### PR TITLE
Update vault_descriptions.php - Removed \ from "you'll"

### PR DESCRIPTION
**Pull request by Stxtics**

### CODE REVIEW

**Comment by bls1999** [comment]
I actually fixed this as part of #162.

**Comment by Stxtics** [comment]
noooooooooooooooooooooooooooo

**Comment by bls1999** [comment]
😂😂😂 sorry bud xD

**Comment by jacob-grahn** [comment]
Thanks Stxtics! I've had the same thing happen to me before. :disappointed_relieved:

**Pull request closed without merging**
