### PR TITLE
Add /priors to /help for mods

### PR DESCRIPTION
**Pull request by Stxtics**
Added the /priors command to the /help command for mods.

### CODE REVIEW

**Comment by famelegend1** [comment]
sticks.... ticks... with the pull request

nice job s t x t i c s

**Comment by Stxtics** [comment]
Oops

**Comment by Stxtics** [comment]
There we go

**Comment by famelegend1** [comment]
just curious, what's the point of these changes? :thinking:

**Comment by bls1999** [comment]
@famelegend1 it just adds /priors to the /help command for mods. I forgot it when I was making it. The multiple commits are a product of an accidental merge with another branch in his repo.

**Comment by Stxtics** [comment]
yeah i saw this so i did it but then realized that I should not of so I reverted everything back 
image

**Comment by jacob-grahn** [comment]
:+1:

**Pull request merged**
