### PR TITLE
Botting patch, slight fixes

### PR DESCRIPTION
**Pull request by bls1999**
HTTP Server:
 - Fixed query in queries/get_info/user.php
 - Created query for pr2_select (check the code, commit 3e97cd5)
 - Fixed player_info.php and semi-updated it to PDO
 - Fixed server crash on admin server owner logout
 - Fixed leaderboard.php

Socket Server:
 - Made `name_to_player()` case insensitive and removed `name_to_id()` calls
 - Fixed/optimized moderation.php, promote_to_moderator.php
 - Disabled and removed +5 EXP bonus
 - Added /hh command (see comments on 93c168a for more details) 
 - Added a check for if the user is winning the artifact (see comments on 927f7f9). Hopefully it works?

There have been reports of botting on levels with a set prize with the +5 EXP bonus, and it's confirmed by those levels' play counts (see The Golden Compass and Hat Factory as examples).  Basically, they enter a level and auto-win as soon as the race starts, collecting the +5 EXP.  Do this a bunch of times and you get an exorbitant amount of EXP.

The easy solution here is to remove the +5 EXP bonus because:
 - The bonus popup doesn't show up in the client anymore
 - It has no effect since EXP has been inflated over the years
 - It would be a lot easier than trying to patch the auto-win glitch, which may require a client edit

If we can patch the auto-win glitch, I wouldn't be opposed to putting the bonus back in the future; However, right now this is a quick fix to stop botting.

### CODE REVIEW

**Comment by jacob-grahn** [comment]
Looks good, I'll get this running on fred

**Comment by EternalUF** [comment]
Woooo! This pull pushed the repo past 1,000 commits congrats all!!!

**Comment by LP-PR2** [comment]
Yay lets not earn any extra exp for winning parts :) way to ruin it for the rest of us.

**Comment by bls1999** [comment]
You can thank the botters for that @LP-PR2.

**Comment by LP-PR2** [comment]
What exactly are they botting and how is it beneficial? Like do you have any proof?

**Comment by LP-PR2** [comment]
I'm sure you do considering who you're getting your information from, i just think it's petty to remove something so small.

**Pull request merged**
