### PR TITLE
Fixed Typo on Ben's staff.php

### PR DESCRIPTION
**Pull request by Antonhs30000**
Fixed typo on line 237.

### CODE REVIEW

**Comment by Antonhs30000** [comment]
That typo caused this, next time make sure to check and run your code before you make a pull request. @bls1999 :3

**Comment by Antonhs30000** [comment]
image

**Comment by bls1999** [comment]
@Antonhs30000

Stxtics and I fixed this in #194.  Please check the pending pull requests before submitting fixes.  Additionally, I'm not sure how you suggest I would've run my code without some major structural modifications since this script contains some database queries that would throw a fatal error on anyone else's server.

If you have a modification to a pull in the future, submit a pull to the author's repo.  It makes more sense and won't clog Jacob's pull request queue.

**Comment by Antonhs30000** [comment]
Ya can use localhost tho @bls1999

**Comment by bls1999** [comment]
Do me a favor and enter the code specifically as it appears on GitHub into your localhost and tell me what you see.

**Pull request closed without merging**
