### PR TITLE
Update guild_create.php

### PR DESCRIPTION
**Pull request by VipaPR2**
Fixed a slight grammatical error and made a small change to the error message returned when an illegal character is used.

### CODE REVIEW

**Comment by bls1999** [comment]
Can you combine this with #233?

**Comment by VipaPR2** [comment]
Ok.

**Comment by VipaPR2** [comment]
Nevermind, I don't know how.

**Comment by bls1999** [comment]
Close this and make the edits on your patch-3 branch https://github.com/VipaPR2/platform-racing-2-server/tree/patch-3

**Pull request closed without merging**
