### PR TITLE
Sanitize email inputs

### PR DESCRIPTION
**Pull request by bls1999**
This pull provides much-needed security updates by sanitizing the email inputs to `forgot_password.php`, `account_change_email.php`, and `register_user.php`.

### CODE REVIEW

**Comment by jacob-grahn** [comment]
Why do we need to remove the extra characters beyond what `FILTER_SANITIZE_EMAIL` does?

**Comment by bls1999** [comment]
The characters removed with str_replace have the potential to cause issues.  We believe this is how @RealShadowZ is able to generate fake email changes to their email address, thereby enabling him to steal accounts.

**Comment by jacob-grahn** [comment]
Ok, that's a fairly convincing argument

**Comment by RealShadowZ** [comment]
Hmm because I didn't take your bait but somehow you have proof that I can do this. HMMMMMM

**Comment by bls1999** [comment]
@RealShadowZ your 15 minutes of fame are over. Bye!

**Comment by famelegend1** [comment]
rip [real], eh? @bls1999

**Pull request merged**
