### PR TITLE
Create staff.php | finally the correct one :p

### PR DESCRIPTION
**Pull request by Antonhs30000**
This is the correct one, merge that, it has function inside and I fixed a typo :p @jacob-grahn

### CODE REVIEW

**Comment by bls1999** [comment]
I have some fixes I'd like to submit for this. Stay tuned.

**Comment by Myst1cZ** [comment]
I see aswell few things that would be good idea to change

**Comment by Antonhs30000** [comment]
Alright, Ben! ^^

**Comment by bls1999** [comment]
okay @jacob-grahn, this is good to merge now.

**Pull request merged**
