### PR TITLE
[Potentially] Fix Liquibase

### PR DESCRIPTION
**Pull request by bls1999**
This contains a potential fix for #731.

### CODE REVIEW

**Comment by bls1999** [comment]
@fourst4r please lmk if this works

**Comment by fourst4r** [comment]
this is still a problem @bls1999 
```
docker-liquibase-1  | Unexpected error running Liquibase: Validation Failed:
docker-liquibase-1  |      1 change sets had duplicate identifiers
docker-liquibase-1  |           liquibase/base.mysql.sql::1574908323264-70::root```

**Comment by fourst4r** [comment]
i fixed it by picking a new ID manually for one of the 70s but idk if that's the ideal solution, might be better to generate an updated schema from the real DB?

**Comment by VipaPR2** [comment]
> 

I agree with this.

**Pull request closed without merging**
