### PR TITLE
Add html prevention in exception message

### PR DESCRIPTION
**Pull request by Myst1cZ**
An small fix on exception to only allow new line tags.
Edit: added another new line only allowed on show_record.php

### CODE REVIEW

**Comment by bls1999** [comment]
Again, this is not needed. The only person that would be able to see that message is the user.

**Comment by Myst1cZ** [comment]
Added only new line tags allowed in ban reason at show_record.php

**Comment by jacob-grahn** [comment]
Thanks Myst1cZ!

**Comment by jacob-grahn** [comment]
It looks like in recent versions of php just using `<br>` will work for `<br>` and `<br/>`

http://php.net/manual/en/function.strip-tags.php

> Note:
> In PHP 5.3.4 and later, self-closing XHTML tags are ignored and only non-self-closing tags should be used in allowable_tags. For example, to allow both `<br>` and `<br/>`, you should use:
> ```php
> <?php
> strip_tags($input, '<br>');
> ?>
> ```

**Pull request merged**
