### PR TITLE
Create leaderboard.php

### PR DESCRIPTION
**Pull request by BrokenBulb78**
On this page you can view all Rank 50+ Users, not sure if it'll work though but let's give it a shot!

### CODE REVIEW

**Comment by BrokenBulb78** [comment]
There's a 2 hour limit, wouldn't that work? @bls1999

**Comment by bls1999** [comment]
Think about how many accounts have ever registered to PR2 and gotten higher than rank 50.  A lot.  That would put a lot of unnecessary strain on the database.
I'm working on this right now; I'll let you know what I figure out.

**Comment by BrokenBulb78** [comment]
Alright ^^

**Comment by woodenstix** [comment]
>implying we need more useless pages

**Comment by BrokenBulb78** [comment]
@woodenstix That's something like rankings. Also, why do you even care since you're banned? :thinking:

**Comment by BrokenBulb78** [comment]
@jacob-grahn Now the pull is ready

**Comment by LP-PR2** [comment]
I can think of a number of games that don't have a 50+ leaderboard. Not to take away from the idea to dig up some secret accounts though (i'm looking at suuper and firebird here ;) )

**Comment by VipaPR2** [comment]
I don't think this is necessary to be honest. Especially if it would overload the database.

**Comment by BrokenBulb78** [comment]
Yup, Vipa is right. It would overload the database. A Rank 50+ list is fine.

**Comment by VipaPR2** [comment]
You're saying I'm right, but then you're saying "A Rank 50+ list is fine.". Make up your mind, lol.

**Comment by BrokenBulb78** [comment]
I mean a rank 0-150 list would overload the database lol

**Comment by VipaPR2** [comment]
No one ever talked about a rank 0-150 rank list. We are talking about rank 50+ list.

**Comment by BrokenBulb78** [comment]
Lel oops, I thought LP wanted to make it a rank 0-150 list, deleting my previous comments xD

**Comment by VipaPR2** [comment]
Nah, if you delete your comments, my comments won't make any sense.

**Comment by BrokenBulb78** [comment]
Then delete them :man_shrugging:

**Comment by VipaPR2** [comment]
Ok.

**Comment by VipaPR2** [comment]
I don't think this is necessary, especially if it will overload the database.

**Comment by bls1999** [comment]
I just submitted a fix for the db overload. @BrokenBulb78

**Comment by BrokenBulb78** [comment]
Done.

**Comment by jacob-grahn** [comment]
Cool!

**Pull request merged**
